### ISSUE TITLE
When is drawRect: called?

### ISSUE THREAD

**Issue by penguin1214** [huzecong/halt-osx#1]
I'm referring your code to make a status bar app. I didn't implement `observeValueForKeyPath: ofObject: change: context:` and `setStatusImageAndToolTip` methods as they are unnecessary in my project. However, I found that the `drawRect:` method is called when `statusItem.length = length;` gets executed. Why?

**Comment by huzecong** [comment]
Hi, it's been a long time since I've written this project, so I can't guarantee what I say is absolutely correct.
The `drawRect:` method is part of the `RHStatusView` module which was not implemented by me. I think this is actually an override of the drawing function of `NSView`, which was inherited by `NSControl`, which was inherited by `RHStatusView`. Upon changing the `length` property, `NSView` refreshes itself automatically and thus calls its `drawRect:` method.

**Comment by penguin1214** [comment]
Why does `NSView` refreshes itself automatically? Does it mean the `NSView` automatically refreshes itself when its properties get changed? I'm quite new to Cocoa and I'm not quite clear about how the `NSView` class work. Sorry about my stupid question.

**Comment by huzecong** [comment]
I think `NSView` triggers a redraw when its size changes. You can check Apple's documentations to make sure.

**Comment by penguin1214** [comment]
Thanks a lot. :)
